# AppVeyor build configuration
# Author(s):       iFarbod <ifarbod@outlook.com>
#
# Copyright (c) 2015-2017 CTNorth Team
#
# Distributed under the MIT license (See accompanying file LICENSE or copy at
# https://opensource.org/licenses/MIT)


#---------------------------------#
#      General configuration      #
#---------------------------------#
version: '{build}'

branches:
  only:
    - master

skip_tags: true

#---------------------------------#
#    Environment configuration    #
#---------------------------------#
image: Visual Studio 2017

clone_depth: 1

#environment:
  #NSIS_ROOT: $(APPVEYOR_BUILD_FOLDER)\Shared\Installer\NSIS

#---------------------------------#
#       Build configuration       #
#---------------------------------#
platform:
  - Win32
  #- x64

configuration: Release

before_build:
  - genversion
  - utils\premake5 install_cef
  - utils\premake5 vs2017

build:
  parallel: true
  project: Build/CTNorth.sln
  verbosity: minimal

after_build:
  - utils\premake5 install_data
  - utils\premake5 compose_files

#---------------------------------#
#      Artifacts configuration    #
#---------------------------------#
#artifacts:
  #- path: CTN-Setup.exe
    #name: CTN

#---------------------------------#
#     Deployment configuration    #
#---------------------------------#
deploy: off

#---------------------------------#
#         Notifications           #
#---------------------------------#
notifications:
  # GitHub PR comment
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
